### ISSUE TITLE
Renovate default images

### ISSUE THREAD

**Issue by bastjan** [projectsyn/steward#101]
Steward contains configuration for images and an image tags to initially deploy ArgoCD. Later on, those deployments will be adopted by Component ArgoCD. The defaults in Steward and Component ArgoCD have drifted apart. In the component, those image tags are kept up to date with Renovate. This should also be the case for the image tags in Steward.

Maybe we could teach Renovate to do this using regex manager.

https://github.com/projectsyn/steward/blob/c24b80c/main.go#L23 and following line.

**Comment by glrf** [comment]
As part of this it would be helpful to also renovate the installed CRDs
