### ISSUE TITLE
ArgoCD v1alpha1 version is deprecated

### ISSUE THREAD

**Issue by megian** [projectsyn/steward#153]
Since the [ArgoCD Operator version 0.8.0](https://github.com/argoproj-labs/argocd-operator/releases/tag/v0.8.0), the v1beta1 is default. Older objects are going to be converted. Steward restores it and this creates a ping-pong every minute:
```
W0725 09:06:10.334131       1 warnings.go:70] ArgoCD v1alpha1 version is deprecated and will be converted to v1beta1 automatically. Moving forward, please use v1beta1 as the ArgoCD API version.
```

**Comment by DebakelOrakel** [comment]
That should not be the case.
Afaik steward does not create ArgoCD resources, it only checks if an ArgoCD is present.
The ArgoCD resource is created by component-argocd.
